/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package pkg304assignment2;

import java.io.File;
import java.io.FileNotFoundException;
import java.util.ArrayList;
import java.util.Scanner;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.filechooser.FileNameExtensionFilter;
import javax.swing.filechooser.FileSystemView;

/**
 *
 * @author Trishen
 */
public class MainFrame extends javax.swing.JFrame {
    ArrayList<Task> data;
    int rows=0,columns=0;
    /**
     * Creates new form MainFrame
     */
    public MainFrame() {
        initComponents();
        jButton1.setVisible(false);
        jButton3.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jButton1.setText("Begin (Display all generations)");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jScrollPane1.setViewportView(jTextArea1);

        jButton2.setText("Select Default File");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton3.setText("Begin (Display final generation)");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jButton4.setText("Select File");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 771, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(22, 22, 22)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jButton4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jButton2, javax.swing.GroupLayout.DEFAULT_SIZE, 195, Short.MAX_VALUE))
                        .addGap(27, 27, 27)
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 213, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 216, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1)
                    .addComponent(jButton2)
                    .addComponent(jButton3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 178, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed

    
                         
        try {
            Scanner sc = new Scanner(new File("input.txt")); 
           
            rows=sc.nextInt();
            
            sc.nextLine();
            //ArrayList<String> alpha = new ArrayList<>();
            columns=sc.nextInt();
            sc.nextLine();
            data = new ArrayList<Task>();
            int count=1;
            while(sc.hasNextLine()){
                String[]line=sc.nextLine().split(" ");
                
               
            char person =(char)(90-(26-count)); 
                
             for (int i = 0; i < columns; i++) {
             
                    Task t = new Task(Integer.parseInt(line[i]), person,""+ (i+1));
                    data.add(t);
                     //System.out.println(line[i]);
                }
            
                count++;
                
            }
            jTextArea1.setText("Successfully read file");
            jButton1.setVisible(true);
              jButton3.setVisible(true);
           //System.out.print(data);
            
            // TODO add your handling code here:
        } catch (FileNotFoundException ex) {
            JOptionPane.showMessageDialog(null, ex.getMessage());
        }
			//System.out.println(selectedFile.getAbsolutePath());
		
        
        
       
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
Population initial = new Population(data, rows,columns);
initial.generateInitialPopulation();
jTextArea1.append("\nCreated initial population");
if(initial.checkTermination()){
    jTextArea1.append("\nCreated Generation "+initial.getGeneration());
   //jTextArea1.append("\n"+initial.getFittest().toString());
      //  jTextArea1.append("\nFittest :\n"+printChromoNames(initial.getFittest().toString()));
        jTextArea1.append("\n"+printChromoValues(initial.getFittest().toString(),initial.getFittest()));
     printOutput(initial.getFittest());
}
else{
    while(initial.checkTermination()!=true){
        initial.generatePopulation();
        jTextArea1.append("\nCreated Generation "+initial.getGeneration());
        printOutput(initial.getFittest());
         
       // jTextArea1.append("\nFittest :\n"+printChromoNames(initial.getFittest().toString()));
       // jTextArea1.append("\n"+printChromoValues(initial.getFittest().toString(),initial.getFittest()));
        jTextArea1.append("\nSum:"+(initial.getFittest().fitness));
    }
    jTextArea1.append("\nSuccess");
}
//boolean terminate = initial.checkTermination();

// TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
       Population initial = new Population(data, rows,columns);
initial.generateInitialPopulation();
jTextArea1.append("\nCreated initial population");
if(initial.checkTermination()){
    jTextArea1.append("\nCreated Generation "+initial.getGeneration());
   //jTextArea1.append("\n"+initial.getFittest().toString());
      //  jTextArea1.append("\nFittest :\n"+printChromoNames(initial.getFittest().toString()));
        jTextArea1.append("\n"+printChromoValues(initial.getFittest().toString(),initial.getFittest()));
     printOutput(initial.getFittest());
}
else{
    while(initial.checkTermination()!=true){
        initial.generatePopulation();
         jTextArea1.append("\nCreated Generation "+initial.getGeneration());
        
    }
    jTextArea1.append("\nCreated Generation "+initial.getGeneration());
        printOutput(initial.getFittest());
         
       // jTextArea1.append("\nFittest :\n"+printChromoNames(initial.getFittest().toString()));
       // jTextArea1.append("\n"+printChromoValues(initial.getFittest().toString(),initial.getFittest()));
        jTextArea1.append("\nSum:"+(initial.getFittest().fitness));
    jTextArea1.append("\nSuccess");
}
//boolean terminate = initial.checkTermination();
 // TODO add your handling code here:
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
 JFileChooser jfc = new JFileChooser(FileSystemView.getFileSystemView().getHomeDirectory());
 File selectedFile;       
 int returnValue = jfc.showOpenDialog(null);
		// int returnValue = jfc.showSaveDialog(null);
                jfc.setDialogTitle("Select an image");
		jfc.setAcceptAllFileFilterUsed(false);
		FileNameExtensionFilter filter = new FileNameExtensionFilter("txt files", "txt");
		jfc.addChoosableFileFilter(filter);
		if (returnValue == JFileChooser.APPROVE_OPTION) {
			 selectedFile = jfc.getSelectedFile();
                         
        try {
            Scanner sc = new Scanner(selectedFile); 
           
            rows=sc.nextInt();
            
            sc.nextLine();
            //ArrayList<String> alpha = new ArrayList<>();
            columns=sc.nextInt();
            sc.nextLine();
            data = new ArrayList<Task>();
            int count=1;
            while(sc.hasNextLine()){
                String[]line=sc.nextLine().split(" ");
                
               
            char person =(char)(90-(26-count)); 
                
             for (int i = 0; i < columns; i++) {
             
                    Task t = new Task(Integer.parseInt(line[i]), person,""+ (i+1));
                    data.add(t);
                     //System.out.println(line[i]);
                }
            
                count++;
                
            }
            jTextArea1.setText("Successfully read file");
            jButton1.setVisible(true);
              jButton3.setVisible(true);
           //System.out.print(data);
            
            // TODO add your handling code here:
        } catch (FileNotFoundException ex) {
            JOptionPane.showMessageDialog(null, ex.getMessage());
        }
			//System.out.println(selectedFile.getAbsolutePath());
		}        // TODO add your handling code here:
    }//GEN-LAST:event_jButton4ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainFrame().setVisible(true);
            }
        });
    }
    
    public void printOutput(Chromosome c){
        jTextArea1.append("\nPerson\tTask\tValue");
        for (int i = 0; i < c.length; i++) {
            String s="";
            int temp = c.chromosome.get(i);
            if(temp!=-1){
                 s =c.getName(i);
                s+="\t";
                s+=c.getTask(i);
                s+="\t";
                s+=c.getValue(i);
            }
            else{
                 s =c.getName(i);
                s+="\t";
                  s+=c.getTask(i);
                s+="\t";
                s+=0;
            }
            jTextArea1.append("\n");
            jTextArea1.append(s);
        }
        
    }
    
    public String printChromoValues(String str,Chromosome c){
         String s = "";
        String[] strArr=str.split(",");
        boolean found = false;
        int index=0;
        for (int i = 0; i < columns; i++) {
            found = false;
            index=0;
            while(!found){
                if(strArr[i].equals(data.get(index).taskID)){
                   if( c.chromosome.get(i)!=-1){
                       s+=data.get(index).value+"  ";
                   }
                   else{
                       s+=0+"  ";
                   }
                    found=true;
                }
                index++;
            }
        }
        return s;
        
    }
   
    public String printChromoNames(String str){
        String s = "";
        String[] strArr=str.split(",");
        boolean found = false;
        int index=0;
        for (int i = 0; i < rows; i++) {
            found = false;
            index=0;
            while(!found){
                if(strArr[i].equals(data.get(index).taskID)){
                    s+=data.get(index).person+"  ";
                    found=true;
                }
                index++;
            }
        }
        return s;
        
    }
    
   
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea jTextArea1;
    // End of variables declaration//GEN-END:variables
}
